#!/usr/bin/env python3
"""
Motion Log Visualizer

Loads and visualizes motion log data from CSV files generated by the motion logger.
Usage: python visualize_motion_log.py <logfile>
       python visualize_motion_log.py logs/test1.log
"""

import sys
import os
import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec


def load_log_file(filepath: str) -> pd.DataFrame:
    """Load a motion log CSV file into a pandas DataFrame."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Log file not found: {filepath}")
    
    df = pd.read_csv(filepath)
    return df


def plot_poses(ax_pos, ax_ori, df: pd.DataFrame, pose_type: str = 'tcp'):
    """Plot position and orientation for TCP or flange."""
    time = df['elapsed_time_s']
    
    if pose_type == 'tcp':
        prefix = 'tcp_'
        title_prefix = 'TCP'
        colors = ['#e41a1c', '#377eb8', '#4daf4a']  # red, blue, green
    else:
        prefix = 'flange_'
        title_prefix = 'Flange'
        colors = ['#984ea3', '#ff7f00', '#a65628']  # purple, orange, brown
    
    # Position plot
    ax_pos.plot(time, df[f'{prefix}x'] * 1000, label='X', color=colors[0], linewidth=1.5)
    ax_pos.plot(time, df[f'{prefix}y'] * 1000, label='Y', color=colors[1], linewidth=1.5)
    ax_pos.plot(time, df[f'{prefix}z'] * 1000, label='Z', color=colors[2], linewidth=1.5)
    ax_pos.set_xlabel('Time (s)')
    ax_pos.set_ylabel('Position (mm)')
    ax_pos.set_title(f'{title_prefix} Position')
    ax_pos.legend(loc='upper right')
    ax_pos.grid(True, alpha=0.3)
    
    # Orientation plot (axis-angle)
    ax_ori.plot(time, df[f'{prefix}rx'], label='Rx', color=colors[0], linewidth=1.5)
    ax_ori.plot(time, df[f'{prefix}ry'], label='Ry', color=colors[1], linewidth=1.5)
    ax_ori.plot(time, df[f'{prefix}rz'], label='Rz', color=colors[2], linewidth=1.5)
    ax_ori.set_xlabel('Time (s)')
    ax_ori.set_ylabel('Orientation (rad)')
    ax_ori.set_title(f'{title_prefix} Orientation (axis-angle)')
    ax_ori.legend(loc='upper right')
    ax_ori.grid(True, alpha=0.3)


def plot_forces(ax_force, ax_torque, df: pd.DataFrame, frame: str = 'base'):
    """Plot forces and torques.
    
    Args:
        ax_force: Axes for force plot
        ax_torque: Axes for torque plot
        df: DataFrame with motion data
        frame: 'base' for base frame forces, 'tcp' for TCP local frame forces
    """
    time = df['elapsed_time_s']
    
    # Determine column prefix based on frame
    if frame == 'tcp':
        force_prefix = 'force_tcp_'
        torque_prefix = 'torque_tcp_'
        title_suffix = ' (TCP Frame)'
    else:
        force_prefix = 'force_base_'
        torque_prefix = 'torque_base_'
        title_suffix = ' (Base Frame)'
    
    # Check if new column names exist, fall back to old names for backward compatibility
    if f'{force_prefix}fx' not in df.columns:
        # Old format - single set of force columns
        force_prefix = 'force_'
        torque_prefix = 'torque_'
        title_suffix = ''
    
    # Force plot
    ax_force.plot(time, df[f'{force_prefix}fx'], label='Fx', color='#e41a1c', linewidth=1.5)
    ax_force.plot(time, df[f'{force_prefix}fy'], label='Fy', color='#377eb8', linewidth=1.5)
    ax_force.plot(time, df[f'{force_prefix}fz'], label='Fz', color='#4daf4a', linewidth=1.5)
    ax_force.set_xlabel('Time (s)')
    ax_force.set_ylabel('Force (N)')
    ax_force.set_title(f'TCP Forces{title_suffix}')
    ax_force.legend(loc='upper right')
    ax_force.grid(True, alpha=0.3)
    ax_force.axhline(y=0, color='black', linestyle='-', linewidth=0.5)
    
    # Torque plot
    ax_torque.plot(time, df[f'{torque_prefix}mx'], label='Mx', color='#984ea3', linewidth=1.5)
    ax_torque.plot(time, df[f'{torque_prefix}my'], label='My', color='#ff7f00', linewidth=1.5)
    ax_torque.plot(time, df[f'{torque_prefix}mz'], label='Mz', color='#a65628', linewidth=1.5)
    ax_torque.set_xlabel('Time (s)')
    ax_torque.set_ylabel('Torque (Nm)')
    ax_torque.set_title(f'TCP Torques{title_suffix}')
    ax_torque.legend(loc='upper right')
    ax_torque.grid(True, alpha=0.3)
    ax_torque.axhline(y=0, color='black', linestyle='-', linewidth=0.5)


def plot_3d_trajectory(ax, df: pd.DataFrame):
    """Plot 3D trajectory of TCP."""
    # Convert to mm for better readability
    x = df['tcp_x'] * 1000
    y = df['tcp_y'] * 1000
    z = df['tcp_z'] * 1000
    
    # Color by time
    time = df['elapsed_time_s']
    
    # Create scatter plot with color gradient
    scatter = ax.scatter(x, y, z, c=time, cmap='viridis', s=2, alpha=0.8)
    
    # Plot start and end points
    ax.scatter([x.iloc[0]], [y.iloc[0]], [z.iloc[0]], 
               color='green', s=100, marker='o', label='Start', zorder=5)
    ax.scatter([x.iloc[-1]], [y.iloc[-1]], [z.iloc[-1]], 
               color='red', s=100, marker='s', label='End', zorder=5)
    
    ax.set_xlabel('X (mm)')
    ax.set_ylabel('Y (mm)')
    ax.set_zlabel('Z (mm)')
    ax.set_title('TCP 3D Trajectory')
    ax.legend(loc='upper left')
    
    # Add colorbar
    plt.colorbar(scatter, ax=ax, label='Time (s)', shrink=0.5)


def plot_force_magnitude(ax, df: pd.DataFrame, frame: str = 'base'):
    """Plot force and torque magnitudes over time.
    
    Args:
        ax: Axes for plot
        df: DataFrame with motion data
        frame: 'base' for base frame forces, 'tcp' for TCP local frame forces
    """
    time = df['elapsed_time_s']
    
    # Determine column prefix based on frame
    if frame == 'tcp':
        force_prefix = 'force_tcp_'
        torque_prefix = 'torque_tcp_'
        title_suffix = ' (TCP Frame)'
    else:
        force_prefix = 'force_base_'
        torque_prefix = 'torque_base_'
        title_suffix = ' (Base Frame)'
    
    # Check if new column names exist, fall back to old names for backward compatibility
    if f'{force_prefix}fx' not in df.columns:
        force_prefix = 'force_'
        torque_prefix = 'torque_'
        title_suffix = ''
    
    # Calculate magnitudes
    force_mag = np.sqrt(df[f'{force_prefix}fx']**2 + df[f'{force_prefix}fy']**2 + df[f'{force_prefix}fz']**2)
    torque_mag = np.sqrt(df[f'{torque_prefix}mx']**2 + df[f'{torque_prefix}my']**2 + df[f'{torque_prefix}mz']**2)
    
    ax.plot(time, force_mag, label='|Force| (N)', color='#e41a1c', linewidth=1.5)
    ax.plot(time, torque_mag, label='|Torque| (Nm)', color='#377eb8', linewidth=1.5)
    ax.set_xlabel('Time (s)')
    ax.set_ylabel('Magnitude')
    ax.set_title(f'Force and Torque Magnitudes{title_suffix}')
    ax.legend(loc='upper right')
    ax.grid(True, alpha=0.3)


def print_statistics(df: pd.DataFrame):
    """Print summary statistics of the motion log."""
    duration = df['elapsed_time_s'].iloc[-1]
    num_samples = len(df)
    sample_rate = num_samples / duration if duration > 0 else 0
    
    print("\n" + "="*60)
    print("MOTION LOG STATISTICS")
    print("="*60)
    print(f"Duration: {duration:.2f} s")
    print(f"Samples: {num_samples}")
    print(f"Sample rate: {sample_rate:.1f} Hz")
    print()
    
    # TCP position range
    print("TCP Position Range (mm):")
    print(f"  X: [{df['tcp_x'].min()*1000:.2f}, {df['tcp_x'].max()*1000:.2f}]")
    print(f"  Y: [{df['tcp_y'].min()*1000:.2f}, {df['tcp_y'].max()*1000:.2f}]")
    print(f"  Z: [{df['tcp_z'].min()*1000:.2f}, {df['tcp_z'].max()*1000:.2f}]")
    print()
    
    # Determine column names (new or old format)
    has_new_format = 'force_base_fx' in df.columns
    
    if has_new_format:
        # Force statistics (Base Frame)
        print("Force Statistics (Base Frame):")
        print(f"  Fx: mean={df['force_base_fx'].mean():.2f} N, max={df['force_base_fx'].abs().max():.2f} N")
        print(f"  Fy: mean={df['force_base_fy'].mean():.2f} N, max={df['force_base_fy'].abs().max():.2f} N")
        print(f"  Fz: mean={df['force_base_fz'].mean():.2f} N, max={df['force_base_fz'].abs().max():.2f} N")
        print()
        
        # Force statistics (TCP Frame)
        print("Force Statistics (TCP Local Frame):")
        print(f"  Fx: mean={df['force_tcp_fx'].mean():.2f} N, max={df['force_tcp_fx'].abs().max():.2f} N")
        print(f"  Fy: mean={df['force_tcp_fy'].mean():.2f} N, max={df['force_tcp_fy'].abs().max():.2f} N")
        print(f"  Fz: mean={df['force_tcp_fz'].mean():.2f} N, max={df['force_tcp_fz'].abs().max():.2f} N")
        print()
        
        # Torque statistics (Base Frame)
        print("Torque Statistics (Base Frame):")
        print(f"  Mx: mean={df['torque_base_mx'].mean():.2f} Nm, max={df['torque_base_mx'].abs().max():.2f} Nm")
        print(f"  My: mean={df['torque_base_my'].mean():.2f} Nm, max={df['torque_base_my'].abs().max():.2f} Nm")
        print(f"  Mz: mean={df['torque_base_mz'].mean():.2f} Nm, max={df['torque_base_mz'].abs().max():.2f} Nm")
        print()
        
        # Torque statistics (TCP Frame)
        print("Torque Statistics (TCP Local Frame):")
        print(f"  Mx: mean={df['torque_tcp_mx'].mean():.2f} Nm, max={df['torque_tcp_mx'].abs().max():.2f} Nm")
        print(f"  My: mean={df['torque_tcp_my'].mean():.2f} Nm, max={df['torque_tcp_my'].abs().max():.2f} Nm")
        print(f"  Mz: mean={df['torque_tcp_mz'].mean():.2f} Nm, max={df['torque_tcp_mz'].abs().max():.2f} Nm")
    else:
        # Old format - single set of force columns
        print("Force Statistics:")
        print(f"  Fx: mean={df['force_fx'].mean():.2f} N, max={df['force_fx'].abs().max():.2f} N")
        print(f"  Fy: mean={df['force_fy'].mean():.2f} N, max={df['force_fy'].abs().max():.2f} N")
        print(f"  Fz: mean={df['force_fz'].mean():.2f} N, max={df['force_fz'].abs().max():.2f} N")
        print()
        
        # Torque statistics
        print("Torque Statistics:")
        print(f"  Mx: mean={df['torque_mx'].mean():.2f} Nm, max={df['torque_mx'].abs().max():.2f} Nm")
        print(f"  My: mean={df['torque_my'].mean():.2f} Nm, max={df['torque_my'].abs().max():.2f} Nm")
        print(f"  Mz: mean={df['torque_mz'].mean():.2f} Nm, max={df['torque_mz'].abs().max():.2f} Nm")
    
    print("="*60 + "\n")


def visualize_motion_log(filepath: str, show_flange: bool = False):
    """Main visualization function."""
    # Load data
    print(f"Loading log file: {filepath}")
    df = load_log_file(filepath)
    
    # Print statistics
    print_statistics(df)
    
    # Check if new format (both base and TCP frame forces)
    has_dual_forces = 'force_base_fx' in df.columns and 'force_tcp_fx' in df.columns
    
    # Create figure with subplots
    if show_flange:
        if has_dual_forces:
            # New format with both force frames
            fig = plt.figure(figsize=(16, 18))
            gs = GridSpec(5, 2, figure=fig, hspace=0.35, wspace=0.25)
        else:
            fig = plt.figure(figsize=(16, 14))
            gs = GridSpec(4, 2, figure=fig, hspace=0.35, wspace=0.25)
        
        # TCP plots
        ax_tcp_pos = fig.add_subplot(gs[0, 0])
        ax_tcp_ori = fig.add_subplot(gs[0, 1])
        plot_poses(ax_tcp_pos, ax_tcp_ori, df, 'tcp')
        
        # Flange plots
        ax_flange_pos = fig.add_subplot(gs[1, 0])
        ax_flange_ori = fig.add_subplot(gs[1, 1])
        plot_poses(ax_flange_pos, ax_flange_ori, df, 'flange')
        
        # Force/Torque plots (Base Frame)
        ax_force_base = fig.add_subplot(gs[2, 0])
        ax_torque_base = fig.add_subplot(gs[2, 1])
        plot_forces(ax_force_base, ax_torque_base, df, frame='base')
        
        if has_dual_forces:
            # Force/Torque plots (TCP Frame)
            ax_force_tcp = fig.add_subplot(gs[3, 0])
            ax_torque_tcp = fig.add_subplot(gs[3, 1])
            plot_forces(ax_force_tcp, ax_torque_tcp, df, frame='tcp')
            
            # Additional plots
            ax_3d = fig.add_subplot(gs[4, 0], projection='3d')
            plot_3d_trajectory(ax_3d, df)
            
            ax_mag = fig.add_subplot(gs[4, 1])
            plot_force_magnitude(ax_mag, df, frame='tcp')
        else:
            # Additional plots
            ax_3d = fig.add_subplot(gs[3, 0], projection='3d')
            plot_3d_trajectory(ax_3d, df)
            
            ax_mag = fig.add_subplot(gs[3, 1])
            plot_force_magnitude(ax_mag, df)
    else:
        if has_dual_forces:
            # New format with both force frames
            fig = plt.figure(figsize=(16, 14))
            gs = GridSpec(4, 2, figure=fig, hspace=0.35, wspace=0.25)
        else:
            fig = plt.figure(figsize=(16, 10))
            gs = GridSpec(3, 2, figure=fig, hspace=0.35, wspace=0.25)
        
        # TCP plots
        ax_tcp_pos = fig.add_subplot(gs[0, 0])
        ax_tcp_ori = fig.add_subplot(gs[0, 1])
        plot_poses(ax_tcp_pos, ax_tcp_ori, df, 'tcp')
        
        # Force/Torque plots (Base Frame)
        ax_force_base = fig.add_subplot(gs[1, 0])
        ax_torque_base = fig.add_subplot(gs[1, 1])
        plot_forces(ax_force_base, ax_torque_base, df, frame='base')
        
        if has_dual_forces:
            # Force/Torque plots (TCP Frame)
            ax_force_tcp = fig.add_subplot(gs[2, 0])
            ax_torque_tcp = fig.add_subplot(gs[2, 1])
            plot_forces(ax_force_tcp, ax_torque_tcp, df, frame='tcp')
            
            # Additional plots
            ax_3d = fig.add_subplot(gs[3, 0], projection='3d')
            plot_3d_trajectory(ax_3d, df)
            
            ax_mag = fig.add_subplot(gs[3, 1])
            plot_force_magnitude(ax_mag, df, frame='tcp')
        else:
            # Additional plots
            ax_3d = fig.add_subplot(gs[2, 0], projection='3d')
            plot_3d_trajectory(ax_3d, df)
            
            ax_mag = fig.add_subplot(gs[2, 1])
            plot_force_magnitude(ax_mag, df)
    
    # Set overall title
    filename = os.path.basename(filepath)
    fig.suptitle(f'Motion Log: {filename}', fontsize=14, fontweight='bold')
    
    plt.tight_layout()
    plt.show()


def main():
    parser = argparse.ArgumentParser(
        description='Visualize motion log data from robot movements.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python visualize_motion_log.py logs/test1.log
  python visualize_motion_log.py logs/flexion_run.log --flange
        """
    )
    parser.add_argument('logfile', help='Path to the motion log CSV file')
    parser.add_argument('--flange', '-f', action='store_true',
                        help='Also show flange pose plots')
    
    args = parser.parse_args()
    
    try:
        visualize_motion_log(args.logfile, show_flange=args.flange)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()

